% -------------------------------------------------------------------
%  Generated by MATLAB on 1-Dec-2015 12:58:26
%  MATLAB version: 8.6.0.267246 (R2015b)
% -------------------------------------------------------------------
saveVarsMat = load('blah.mat');

a = saveVarsMat.a; % <30x60 double> too many elements

clear saveVarsMat;
